/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpi_oop_lab16_service_NativeAverageCalculator */

#ifndef _Included_ua_khpi_oop_lab16_service_NativeAverageCalculator
#define _Included_ua_khpi_oop_lab16_service_NativeAverageCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_khpi_oop_lab16_service_NativeAverageCalculator
 * Method:    average
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_ua_khpi_oop_lab16_service_NativeAverageCalculator_average
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
